### ISSUE TITLE
two conflicts while updating packages

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#74]
![screenshot_20181203_082816](https://user-images.githubusercontent.com/840070/49376524-81be4f00-f6d5-11e8-890e-e99d2e20497c.png)
![screenshot_20181203_082837](https://user-images.githubusercontent.com/840070/49376530-8551d600-f6d5-11e8-842b-750ff180d49e.png)

**Comment by star-buck** [comment]
for skype conflict: rename icon to skype-web?

**Comment by llelectronics** [comment]
Yeah renamed icon to skype-web.
The other issue should be fixed aswell.

**Comment by star-buck** [comment]
still getting this:
![screenshot_20181203_092700](https://user-images.githubusercontent.com/840070/49379669-a74f5680-f6dd-11e8-98aa-1310b27a62eb.png)

**Comment by llelectronics** [comment]
The package is not updated yet on dci. Somehow jenkins failed to pull it from git. Had to manually trigger it again.
